---
apiVersion: v1
kind: Pod
metadata:
  name: kk6gpv-mqtt
spec:
  restartPolicy: OnFailure
  containers:
    - name: application
      image: areed145/kk6gpv-mqtt:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 4000
      livenessProbe:
        exec:
          command:
            - cat
            - /healthy
        initialDelaySeconds: 30
        periodSeconds: 20
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
