---
apiVersion: v1
kind: Pod
metadata:
  name: kk6gpv-mqtt
spec:
  restartPolicy: OnFailure
  containers:
    - name: application
      image: areed145/kk6gpv-mqtt:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 4000
      livenessProbe:
        httpGet:
          path: /ping
          port: 80
          scheme: HTTP
        initialDelaySeconds: 15
        timeoutSeconds: 1
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
