site_name: kk6gpv-mqtt
site_description: "Documentation for kk6gpv-mqtt component of Coconut Barometer site"
site_author: "Adam Reeder"
site_url: "https://areed145.github.io/kk6gpv-mqtt"
docs_dir: docs/
repo_name: "areed145/kk6gpv-mqtt"
repo_url: "https://github.com/areed145/kk6gpv-mqtt"
nav:
  - Reference: index.md
theme:
  name: "material"
  font:
    text: Ubuntu
    code: Ubuntu Mono
plugins:
  - search:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - mqtt
